version: '3'
services:
   python3_humid:
     build:
       context: .
       args:
         UID: $UID
         GID: $GID
     container_name: 'python3_humid'
     working_dir: '/opt/working'
     tty: true
     volumes:
        - ./working:/opt/working
     ports:
      - 5000:5000
     restart: always
